<?php
if( function_exists('acf_add_local_field_group') ) {
    acf_add_local_field_group(array(
        'key' => 'group_6729efed32119',
        'title' => 'chiffres clés',
        'instruction' => "Chiffre clé avec une animation de compteur",
        'fields' => array(
            array(
                'key' => 'field_672b3a375e87a',
                'label' => 'chiffre clé',
                'name' => 'chiffre_cle',
                'type' => 'accordion',
                'open' => 0,
                'multi_expand' => 0,
                'endpoint' => 0,
                'wrapper' => array('width' => '', 'class' => '', 'id' => ''),
            ),
            array(
                'key' => 'field_6784faffb0169',
                'label' => 'Vitesse du compteur',
                'name' => 'vitesse_du_compteur',
                'type' => 'select',
                'choices' => array(
                    '10' => 'chiffre de 0 à 100',
                    '100' => 'chiffre de 100 à 1000',
                    '1000' => 'chiffre de 1000 à 2000',
                    '2000' => 'chiffre de 2000 à 3000',
                    '3000' => 'chiffre au dessus de 3000',
                    '5000' => 'chiffre au dessus de 5000',
                    '10000' => 'chiffre au dessus de 10 000',
                ),
                'default_value' => 10,
                'return_format' => 'value',
                'multiple' => 0,
                'allow_null' => 0,
                'allow_in_bindings' => 1,
                'ui' => 0,
                'ajax' => 0,
                'placeholder' => '',
                'wrapper' => array('width' => '', 'class' => '', 'id' => ''),
            ),
            array(
                'key' => 'field_6729f3d64580b',
                'label' => 'description du chiffre clé haut',
                'name' => 'description_du_chiffre_cle_haut',
                'type' => 'textarea',
                'default_value' => '',
                'maxlength' => '',
                'rows' => '5',
                'placeholder' => '',
                'new_lines' => 'br',
                'wrapper' => array('width' => '', 'class' => '', 'id' => ''),
            ),
            array(
                'key' => 'field_6729efeec46e5',
                'label' => 'nombre',
                'name' => 'nombre',
                'type' => 'number',
                'required' => 1,
                'default_value' => 0,
                'min' => '',
                'max' => '',
                'step' => '',
                'prepend' => '',
                'append' => '',
                'placeholder' => '',
                'wrapper' => array('width' => '', 'class' => '', 'id' => ''),
            ),
            array(
                'key' => 'field_6729f051c46e7',
                'label' => 'poucentage',
                'name' => 'poucentage_check',
                'type' => 'true_false',
                'message' => 'Afficher en pourcentage',
                'default_value' => 0,
                'ui' => 1,
                'allow_in_bindings' => 1,
                'wrapper' => array('width' => '', 'class' => '', 'id' => ''),
            ),
            // Symbole monétaire
        array(
            'key' => 'field_chiffre_symbole_monetaire',
            'label' => 'Symbole monétaire',
            'name' => 'symbole_monetaire',
            'type' => 'select',
            'instructions' => 'Afficher un symbole monétaire (seulement si pourcentage non coché)',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_chiffre_pourcentage',
                        'operator' => '!=',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '100',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                '' => 'Aucun',
                '€' => '€ (Euro)',
                '$' => '$ (Dollar)',
                '£' => '£ (Livre)',
                'CHF' => 'CHF (Franc suisse)',
                '¥' => '¥ (Yen)',
            ),
            'default_value' => '',
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 1,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => 'Choisir un symbole',
        ),
            array(
                'key' => 'field_6729f0b9c46e8',
                'label' => 'description du chiffre clé bas',
                'name' => 'description_du_chiffre_cle_bas',
                'type' => 'textarea',
                'default_value' => '',
                'maxlength' => '',
                'rows' => '',
                'placeholder' => '',
                'new_lines' => '',
                'wrapper' => array('width' => '', 'class' => '', 'id' => ''),
            ),
            array(
                'key' => 'field_67851a49b16cc',
                'label' => 'Icon ou image',
                'name' => 'icon_ou_image',
                'type' => 'true_false',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => 'image',
                'ui_off_text' => 'icon',
                'wrapper' => array('width' => '', 'class' => '', 'id' => ''),
            ),
            array(
                'key' => 'field_6729f935f47e1',
                'label' => 'icon FontAwesome',
                'name' => 'icon_fontawesome',
                'type' => 'select',
                'choices' => array(), // Rempli dynamiquement par JS
                'allow_null' => 1,
                'default_value' => '',
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_67851a49b16cc',
                            'operator' => '!=',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array('width' => '', 'class' => '', 'id' => ''),
            ),
            array(
                'key' => 'field_67851a8531da2',
                'label' => 'image',
                'name' => 'image',
                'type' => 'image',
                'instructions' => 'Fichier png',
                'return_format' => 'url',
                'library' => 'all',
                'mime_types' => 'png',
                'preview_size' => 'full',
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_67851a49b16cc',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array('width' => '', 'class' => '', 'id' => ''),
            ),
            array(
                'key' => 'field_672b3a155e879',
                'label' => 'Couleurs',
                'name' => '',
                'type' => 'accordion',
                'open' => 0,
                'multi_expand' => 0,
                'endpoint' => 0,
                'wrapper' => array('width' => '', 'class' => '', 'id' => ''),
            ),
            array(
                'key' => 'field_672b381b5c3a3',
                'label' => 'Couleur du texte',
                'name' => 'choix_couleurs',
                'type' => 'radio',
                'choices' => array(
                    
                ),
                'default_value' => 'couleur-texte',
                'return_format' => 'value',
                'allow_null' => 0,
                'other_choice' => 0,
                'allow_in_bindings' => 1,
                'layout' => 'vertical',
                'save_other_choice' => 0,
                'wrapper' => array('width' => '', 'class' => '', 'id' => ''),
            ),
            array(
                'key' => 'field_672b39f55e878',
                'label' => 'couleur Chiffre et icon',
                'name' => 'couleur_de_licon',
                'type' => 'radio',
                'choices' => array(
                    
                ),
                'default_value' => 'couleur-lien',
                'return_format' => 'value',
                'allow_null' => 0,
                'other_choice' => 0,
                'allow_in_bindings' => 1,
                'layout' => 'vertical',
                'save_other_choice' => 0,
                'wrapper' => array('width' => '', 'class' => '', 'id' => ''),
            ),
            array(
                'key' => 'field_672b3eec64b21',
                'label' => "couleur d'arrière plan",
                'name' => 'choix_couleurs_copier',
                'type' => 'radio',
                'choices' => array(
                    
                ),
                'default_value' => 'couleur-blanche',
                'return_format' => 'value',
                'allow_null' => 0,
                'other_choice' => 0,
                'allow_in_bindings' => 1,
                'layout' => 'vertical',
                'save_other_choice' => 0,
                'wrapper' => array('width' => '', 'class' => '', 'id' => ''),
            ),
            array(
                'key' => 'field_676432dcecfdf',
                'label' => 'Ombre portée',
                'name' => 'ombre_portee',
                'type' => 'true_false',
                'message' => 'Mettre oui pour afficher une ombre portée.',
                'default_value' => 0,
                'ui' => 1,
                'wrapper' => array('width' => '', 'class' => '', 'id' => ''),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/chiffre',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
    'hide_on_screen' => array('style'),
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
        'modified' => 1736777148,
    ));
}
